import { initializeApp } from 'firebase/app';
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged, User } from 'firebase/auth';
import { initializeFirestore, collection, doc, setDoc, addDoc, getDoc, getDocs, query, where, orderBy, limit, onSnapshot, serverTimestamp, Timestamp } from 'firebase/firestore';

// Import the configuration generated by AI Studio
import firebaseConfig from '../../firebase-applet-config.json';

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// Initialize Firestore with auto-detect long polling for reliable container/iframe connectivity
export const db = initializeFirestore(app, {
  experimentalAutoDetectLongPolling: true,
}, firebaseConfig.firestoreDatabaseId);

export const auth = getAuth(app);
export const googleProvider = new GoogleAuthProvider();

// Error handler helper
export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

export interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string;
    email?: string | null;
    emailVerified?: boolean;
    isAnonymous?: boolean;
    tenantId?: string | null;
    providerInfo?: any[];
  }
}

export function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  const errorCode = (error as any)?.code || '';

  const errInfo: FirestoreErrorInfo = {
    error: errorMessage,
    authInfo: {
      userId: auth.currentUser?.uid,
      email: auth.currentUser?.email,
      emailVerified: auth.currentUser?.emailVerified,
      isAnonymous: auth.currentUser?.isAnonymous,
      tenantId: auth.currentUser?.tenantId,
      providerInfo: auth.currentUser?.providerData.map(provider => ({
        providerId: provider.providerId,
        displayName: provider.displayName,
        email: provider.email,
        photoUrl: provider.photoURL
      })) || []
    },
    operationType,
    path
  };

  const isPermissionError =
    errorCode === 'permission-denied' ||
    errorMessage.toLowerCase().includes('missing or insufficient permissions') ||
    errorMessage.toLowerCase().includes('permission');

  if (isPermissionError) {
    console.error('Firestore Error: ', JSON.stringify(errInfo));
    throw new Error(JSON.stringify(errInfo));
  } else {
    console.warn(`Firestore [${operationType}] at ${path}:`, errorMessage);
  }
}

// Auth Helpers
export const loginWithGoogle = async () => {
  try {
    const result = await signInWithPopup(auth, googleProvider);
    const user = result.user;
    
    // Create/update user profile in Firestore
    const userRef = doc(db, 'users', user.uid);
    await setDoc(userRef, {
      uid: user.uid,
      email: user.email,
      displayName: user.displayName,
      photoURL: user.photoURL,
      lastLogin: new Date().toISOString()
    }, { merge: true });
    
    return user;
  } catch (error) {
    console.error("Login Error:", error);
    throw error;
  }
};

export const logout = () => signOut(auth);

export const getUserProfile = (uid: string, callback: (data: any) => void) => {
  const path = `users/${uid}`;
  return onSnapshot(doc(db, 'users', uid), (docSnap) => {
    callback(docSnap.data());
  }, (error) => {
    handleFirestoreError(error, OperationType.GET, path);
  });
};

// Progression Types & Helpers
export interface ExerciseRecord {
  bestWpm: number;
  bestAccuracy: number;
  stars: number;
  completedAt: string;
  attempts: number;
}

export const saveUserProgression = async (
  uid: string,
  sessionInfo: {
    exerciseId: string;
    exerciseTitle: string;
    wpm: number;
    accuracy: number;
    errors: number;
    correctChars: number;
  },
  currentProfile?: any
) => {
  const path = `users/${uid}`;
  try {
    const userRef = doc(db, 'users', uid);
    const existingSnap = await getDoc(userRef);
    const existingData = existingSnap.exists() ? existingSnap.data() : (currentProfile || {});

    const existingCompleted = existingData.completedExercises || {};
    const prevExerciseRecord = existingCompleted[sessionInfo.exerciseId];

    // Calculate stars: 3 stars (high accuracy & speed), 2 stars (solid), 1 star (completion)
    let earnedStars = 1;
    if (sessionInfo.accuracy >= 96 && sessionInfo.wpm >= 38) {
      earnedStars = 3;
    } else if (sessionInfo.accuracy >= 90 && sessionInfo.wpm >= 20) {
      earnedStars = 2;
    }

    const updatedStars = Math.max(prevExerciseRecord?.stars || 0, earnedStars);
    const updatedBestWpmForEx = Math.max(prevExerciseRecord?.bestWpm || 0, sessionInfo.wpm);
    const updatedBestAccForEx = Math.max(prevExerciseRecord?.bestAccuracy || 0, sessionInfo.accuracy);
    const attempts = (prevExerciseRecord?.attempts || 0) + 1;

    const newCompletedMap = {
      ...existingCompleted,
      [sessionInfo.exerciseId]: {
        bestWpm: updatedBestWpmForEx,
        bestAccuracy: updatedBestAccForEx,
        stars: updatedStars,
        completedAt: new Date().toISOString(),
        attempts
      }
    };

    const totalStars = Object.values(newCompletedMap).reduce((acc: number, item: any) => acc + (item.stars || 0), 0);
    const allTimeBestWpm = Math.max(existingData.bestWpm || 0, sessionInfo.wpm);
    const totalSessions = (existingData.totalSessions || 0) + 1;
    const prevAvg = existingData.averageAccuracy || sessionInfo.accuracy;
    const newAvg = Math.round(((prevAvg * (totalSessions - 1)) + sessionInfo.accuracy) / totalSessions);
    const gainedXp = sessionInfo.correctChars + (earnedStars * 25);
    const totalXp = (existingData.xp || 0) + gainedXp;

    const todayStr = new Date().toISOString().split('T')[0];
    let streak = existingData.streak || 1;
    const lastDate = existingData.lastStreakDate;
    if (lastDate) {
      const yesterday = new Date();
      yesterday.setDate(yesterday.getDate() - 1);
      const yesterdayStr = yesterday.toISOString().split('T')[0];
      if (lastDate === yesterdayStr) {
        streak += 1;
      } else if (lastDate !== todayStr) {
        streak = 1;
      }
    }

    const existingDaily = existingData.dailyActivity || {};
    const updatedDaily = {
      ...existingDaily,
      [todayStr]: (existingDaily[todayStr] || 0) + 1
    };
    const longestStreak = Math.max(existingData.longestStreak || 0, streak);

    const updatePayload: any = {
      uid,
      completedExercises: newCompletedMap,
      starsCount: totalStars,
      bestWpm: allTimeBestWpm,
      totalSessions,
      averageAccuracy: newAvg,
      xp: totalXp,
      streak,
      longestStreak,
      dailyActivity: updatedDaily,
      lastStreakDate: todayStr,
      currentExerciseId: sessionInfo.exerciseId,
      lastLogin: new Date().toISOString()
    };

    await setDoc(userRef, updatePayload, { merge: true });

    return {
      earnedStars,
      totalStars,
      allTimeBestWpm,
      totalXp,
      gainedXp
    };
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, path);
    throw error;
  }
};

export const updateUserXP = async (uid: string, xpIncrement: number) => {
  const path = `users/${uid}`;
  try {
    const userRef = doc(db, 'users', uid);
    const userDoc = await getDoc(userRef);
    if (userDoc.exists()) {
      const currentXP = userDoc.data().xp || 0;
      await setDoc(userRef, { uid, xp: currentXP + xpIncrement }, { merge: true });
    } else {
      await setDoc(userRef, { uid, xp: xpIncrement }, { merge: true });
    }
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, path);
  }
};

export const updateUserBadges = async (uid: string, badges: string[]) => {
  const path = `users/${uid}`;
  try {
    const userRef = doc(db, 'users', uid);
    await setDoc(userRef, { uid, badges }, { merge: true });
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, path);
  }
};

// Session Helpers
export const saveSession = async (sessionData: {
  userId: string;
  wpm: number;
  accuracy: number;
  errors: number;
  exerciseTitle: string;
  userName?: string | null;
  userPhoto?: string | null;
}) => {
  const path = 'sessions';
  try {
    await addDoc(collection(db, path), {
      ...sessionData,
      date: new Date().toISOString()
    });
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, path);
  }
};

export const getLeaderboard = (callback: (sessions: any[]) => void) => {
  const path = 'sessions';
  const q = query(
    collection(db, path),
    orderBy('wpm', 'desc'),
    limit(10)
  );

  return onSnapshot(q, (snapshot) => {
    const sessions = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
    callback(sessions);
  }, (error) => {
    handleFirestoreError(error, OperationType.LIST, path);
  });
};
